allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  core-js: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js
  - cypress
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
